title: "Study-Notes"
description: "学习笔记与技术沉淀"
baseurl: "/Study-Notes"
url: ""
timezone: "Asia/Shanghai"
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
repository: xpd-star/Study-Notes
plugins:
  - jekyll-feed
  - jekyll-sitemap
